### ISSUE TITLE
Broken link to ETN explanation

### ISSUE THREAD

**Issue by kdambekalns** [breck7/ohayo#1]
The link https://github.com/breck7/ohayo/blob/master/2017-06-21-show-hn-programming-is-now-two-dimensional.html points to a 404.

**Comment by breck7** [comment]
Thanks for the report @kdambekalns ! Do you now what page this link is on? (I may have removed the page)

**Comment by kdambekalns** [comment]
I'm pretty sure it was in the README… seems to have been fixed.

**Comment by breck7** [comment]
Yes it likely was, makes sense, thanks!
