### ISSUE TITLE
The statement in readme might be outdated

### ISSUE THREAD

**Issue by alexey-milovidov** [breck7/ohayo#85]
I'm reading the readme and found this:

> Ohayo hopefully will be stable by July 2020.

It talks about July 2020 like this is still in the future.

**Comment by breck7** [comment]
Can you send a PR to fix it @alexey-milovidov ? How about say `July 2023`. I bet we could hit that.

**Comment by alexey-milovidov** [comment]
Sorry, I forgot to send a PR. Thank you for updating!
