### ISSUE TITLE
is there a keyboard shortcut: to update the right-hand side of Ohayo (while editing on the left)?

### ISSUE THREAD

**Issue by martin12333** [breck7/ohayo#90]
(I know, I can click to the right-hand side with the mouse to update)

**Comment by breck7** [comment]
great question! the docs say cmd+s, but not 100% sure, and I think that's Mac only. might want to try that or ctrl+s

<img width="944" alt="Screen Shot 2022-10-13 at 9 58 42 AM" src="https://user-images.githubusercontent.com/74692/195659192-1781924b-5432-4929-aba0-b419596aaa29.png">

**Comment by martin12333** [comment]
windows: ctrl+s
